### ISSUE TITLE
JESGOサポートツールについての機能相談・要望について

### ISSUE THREAD

**Issue by akihikoueda** [piyotaicho/jesgosupport#1]
平素よりお世話になっております。JESGOサポートツールでルール作成を行なっておりますが以下の点についてご教示、ご対応をお願いしたくご連絡をさしあげました。

**1) 全患者情報ドキュメントからの年齢取得方法**
全患者情報出力の時点では、date_of_birth に患者の生年月日情報が出力されていますが、腫瘍登録に必要な年齢情報はどのように変換取得すればよろしいでしょうか？ 

**2) 開始位置の指定について**
腫瘍登録のデータは 7行目より開始となっており、最初の6行について空けておく必要があります。
書き出し位置を7行目より開始とする方法はありますでしょうか？

**3) 正規表現についての確認**
初回治療開始日について例えば、チェックを行う場合に、変数に初回治療開始日を代入し、当該変数に対して、"置換" により、元の値 : /^[0-9]{4}/g、変換後の値 /[0-9]{4}/ とするとうまくいかず、変換後の値に記載した、"/[0-9]{4}/" がそのまま出力されます。2022のみを抜き出す、2022-01-31 → 2022/01/31 に変換して出力 をしたいと考えておりますが、正規表現での置換でどのように記載すればよろしいでしょうか？

**4) 初回治療の治療方法の出力について**
腫瘍登録においては、治療方法を時系列順に並べ、例えば、「化学療法」、「手術（骨盤・傍大動脈リンパ節郭清を伴う）」、「化学療法」などと出力する必要がありますが、現行のツールですとこの部分の出力制御が難しいように思います。また、手術療法の選択として「手術（骨盤・傍大動脈リンパ節郭清を伴う）」、「手術（骨盤リンパ節郭清のみを伴う）」、「手術（リンパ節郭清を伴わない）」の区分に変換する必要がありますが、手術療法のデータの持ち方を考えると、$.[0].患者台帳.初回治療.手術療法.[0].実施手術.[0].術式 、$.[0].患者台帳.初回治療.手術療法.[0].実施手術.[1].術式、$.[0].患者台帳.初回治療.手術療法.[0].実施手術.[2].術式と順に見ていく必要があり、また、手術が複数回行われているパターンでは、$.[0].患者台帳.初回治療.手術療法.[1].実施手術.[0].術式 からのパターンも考える必要があるため、条件分岐が複雑になってしまいます。この辺りは治療経過サマリに該当する部分と思いますがよい書き出し方法はありますでしょうか？

なお、私見ですが上記を実現するには以下のような機能が必要と考えます。
初回治療について、治療順に沿って治療を並べることを考えると、現行の条件分岐と変数では表現ができないと考えます。
一旦、手術、化学療法、放射線治療について、それぞれの治療開始日時順 (複数回手術や化学療法等行なっている可能性もあり、その場合も想定しての書き出し必要) で並べて、どの順で治療が行われているか、パスが動的に指定できるようにする必要があると考えます。
さらに手術療法について、術式内を全て参照して、術式のカテゴリを選択した上で、治療法に格納する必要があります。
この際、腫瘍登録への登録時に、子宮頸がん、子宮体がんでは 「手術（骨盤・傍大動脈リンパ節郭清を伴う）」、「手術（骨盤リンパ節郭清のみを伴う）」、「手術（リンパ節郭清を伴わない）」という区分であることに対して、卵巣がんでは「生検のみ」「片側付属器摘出術（嚢腫摘出術含む）」「両側付属器摘出術」「子宮摘出術（腟上部切断術を含む）」「大網切除術」「所属リンパ節の摘出（生検または郭清）」「その他（他臓器の合併切除等）」から**複数選択**を行い、治療法に格納する形となっています。このため、術式内から特定の術式がないかを探索し、カテゴリを付与して掃き出し用のデータを作る必要があると思います。

(必要機能1) それぞれの治療における治療開始日の順にパスを並べる機能 

初回治療①：$.[0].患者台帳.初回治療.化学療法.[0]. 治療区分
　　　　　　> 「化学療法」「分子標的治療」「化学療法+分子標的治療」「その他治療」の区分を取得し判定。
　　　　　　　* 子宮体がんの場合は「その他治療」のうち、以下のホルモン療法該当薬使用の場合は、
　　　　　　　  ホルモン療法のフラグ設定が必要。「"メドロキシプロゲステロン酢酸エステル(MPA)", "アナストロゾール"」
初回治療②：$.[0].患者台帳.初回治療.手術療法.[0].実施手術
初回治療③：$.[0].患者台帳.初回治療.化学療法.[1].治療区分
　　　　　　> 「化学療法」「分子標的治療」「化学療法および分子標的治療」「ホルモン治療」「その他治療」の区分を取得し判定。
初回治療④：$.[0].患者台帳.初回治療.放射線療法.[0].治療区分
　　　　　　> 「腔内照射」「体外照射」「同時化学放射線療法（腔内照射）」「同時化学放射線療法（体外照射）」の区分を取得し判定。　
、、、

(必要機能2) パスを一部ワイルドカードで指定し、当該中に含まれる項目をリスト抽出する機能
例: $.[0].患者台帳.初回治療.手術療法.[0].実施手術.*.術式 のように パス中に"*"をおき、階層下の特定のラベルパスを探索し、結果をリストで返す。
(これは現行の抽出機能でワイルドカード指定すれば達成可能でしょうか？）

(必要機能3) リスト抽出した項目中に、別のリストで指定した項目が入っていないか、リスト vs リストで探索し"あり" "なし"を判定し変数として格納する機能
例: 上記で返却されたリスト中に特定の術式 (リスト指定) が入っているかをリスト同士でぶつけて "あり" "なし"を判定し変数として格納する。
(これは現行の条件指定機能でリストをすれば達成可能でしょうか？）

(必要機能4) 出力リストを変数として指定、特定の条件を満たす場合に当該項目をリスト変数へappendできるようにする。また、作成したリストをエクセルの指定領域に出力する機能：
例: 卵巣がんにおいては「初回治療①: 化学療法 → 初回治療②: 手術療法(両側付属器摘出術, 子宮摘出術（腟上部切断術を含む), 大網切除術,所属リンパ節の摘出（生検または郭清）→ 初回治療③: 化学療法と分子標的治療の同時併用」の場合、[8 → 3, 4, 5, 6 → 11]となり、セル出力は 初回治療が3つにもかかわらず、8, 3, 4, 5, 6, 11 として出力する必要があります。このため、初回治療選択結果リストを変数として指定し、初回治療選択結果リストに特定の条件を満たす場合にその結果をappendする (上記の場合、両側付属器摘出術に該当する術式があれば 3 をリストにappendするといった具合)機能があればと考えます。また、エクセルの出力領域は決まっているため、作成したリストについて「R:AC」のように出力先のエクセル範囲を指定し (少し面倒になりますが リスト変数の [0]番目 → [R]列 と一つ一つ指定でも結構です) 出力できるようにする機能がいただきたいです。

なお、実際に行いたい判定は以下のようなイメージとなります。
> 子宮体がん/子宮頸がん：以下のような方法での絞り込みが必要です。
実施手術下の [0]〜[n]の登録術式を探索し、「"腟上部切断術", "単純子宮全摘出術(筋膜内)", "単純子宮全摘出術(筋膜外)", "拡大子宮全摘術", "準広汎子宮全摘出術", "準広汎子宮頸部摘出術", "広汎子宮全摘出術", "広汎子宮全摘出術(神経温存術式)", "広汎子宮頸部摘出術", "腟式単純子宮全摘術(筋膜内)", "腟式準広汎子宮全摘術(筋膜外)", "腟式広汎子宮全摘出術", "腟式広汎子宮頸部摘出術","腹腔鏡下単純子宮全摘出術(筋膜内)", "腹腔鏡下単純子宮全摘出術(筋膜外)", "腹腔鏡下準広汎子宮全摘出術", "腹腔鏡下広汎子宮全摘出術", "腹腔鏡下子宮頸部摘出術", "ロボット支援下単純子宮全摘出術", "ロボット支援下準広汎子宮全摘出術", "ロボット支援下広汎子宮全摘出術", "ロボット支援下子宮頸部摘出術"」があれば、"子宮摘出フラグ ON"とする。「"骨盤リンパ節選択的郭清 (生検)", "骨盤リンパ節系統的郭清", "骨盤リンパ節センチネルリンパ節生検", "腹腔鏡下骨盤内リンパ節郭清"」があれば、"骨盤内リンパ節郭清フラグ ON"とする。「"傍大動脈リンパ節選択的郭清 (生検)", "傍大動脈リンパ節系統的郭清", "傍大動脈リンパ節センチネルリンパ節生検", "腹腔鏡下傍大動脈リンパ節郭清"」があれば、"傍大動脈リンパ節郭清フラグ ON"とする。"子宮摘出フラグ ON"で他が OFFなら「手術（リンパ節郭清を伴わない）」にカテゴライズする。"子宮摘出フラグ ON"、"骨盤内リンパ節郭清フラグ ON"、"傍大動脈リンパ節郭清フラグ OFF"なら「手術（骨盤リンパ節郭清のみを行う）」にカテゴライズする。"子宮摘出フラグ ON"、"骨盤内リンパ節郭清フラグ OFF"、"傍大動脈リンパ節郭清フラグ OFF"なら「手術（骨盤・傍大動脈リンパ節郭清を行う）」にカテゴライズする。(アウトプットは1つの治療)
> 卵巣がん：卵巣がんの場合は生検のみ」「片側付属器摘出術（嚢腫摘出術含む）」「両側付属器摘出術」「子宮摘出術（腟上部切断術を含む）」「大網切除術」「所属リンパ節の摘出（生検または郭清）」「その他（他臓器の合併切除等）」から複数選択を行い、治療法に格納する形となっていることが煩雑となっています。上記の子宮体がん、頸がんのイメージで、術式からの条件探索を行なってそれぞれの有無を判定し、ONのものを列挙してリストで書き出すイメージとなりますでしょうか。

以上が詰まっているところでしてご教示いただけますと幸いです。

**Comment by piyotaicho** [comment]
実装にかまけて、テスト中ですが、簡単に行けるところから。
(3)の日付フォーマット変更は以下のシンタックスが使えます。ちなみに、正規表現の//gはキャンセルする仕様です。
![image](https://github.com/piyotaicho/jesgosupport/assets/57445173/aaca35e0-4978-47c9-932c-2e82be35b34a)

**Comment by piyotaicho** [comment]
(2)は次のリリースで仕込みました。CSVの保存でオフセット指定できます。
![image](https://github.com/piyotaicho/jesgosupport/assets/57445173/18003471-f9c2-4f91-8f8f-81f53db2adf7)

**Comment by akihikoueda** [comment]
(2), (3) についてご教示いただきありがとうございます。
(3)については早速試したいと存じます。

**Comment by piyotaicho** [comment]
JESGOのプラグインがなぜか動かないので修正中ですが、0.3.0をアップしました。
ソートも入れたので、こんなこともできるようになりました。
![image](https://github.com/piyotaicho/jesgosupport/assets/57445173/fd6e705f-90a1-4f6f-8ca9-5b3490296c36)

**Comment by piyotaicho** [comment]
出力のアレイ連結を umin の ; 区切り設定できるものをmergeするのを忘れたので、早々に次を用意します。

**Comment by akihikoueda** [comment]
version 0.30 の実装ありがとうございます。
出力アレイ連結についてですが、腫瘍登録では周産期登録のような  " ; 区切り設定" がなく、
択一で選択する項目しかないため、「 " ; 区切り設定"」の対応は "なし" でよいかと考えております。
現行作成いただいたツールにて早急にルール作成を進めさせて頂きます。
