### ISSUE TITLE
重複がんの場合のパス設定のご相談

### ISSUE THREAD

**Issue by akihikoueda** [piyotaicho/jesgosupport#2]
追加でポストさせて頂きます。
症例はあまり多くないですが、"重複がん"の場合において、現行では患者台帳は登録順に格納されるため、JSONパスの設定で、「$.[0].患者台帳.[0]」「$.[0].患者台帳.[1]」「$.[0].患者台帳.[2]」、、のどこにあるかを探す必要があるように思われます。

今の所、ソース指定の条件分岐において 「がん種」、「初回治療開始年月日」、「腫瘍登録対象」をチェックし、条件が合致しない場合に、参照先を「$.[0].患者台帳.[1]」「$.[0].患者台帳.[2]」と変えるしかないかと思っておりますが、スマートな方法はありますでしょうか？ 

理想を言いますと、腫瘍登録画面で検索し出力する際に腫瘍による絞り込みを行うため、当該腫瘍の台帳のみがDocumentに反映され出力される機能などがあるとありがたいかと思いました。

**Comment by piyotaicho** [comment]
これも、腫瘍登録は癌腫ごとなので不要な台帳データを触らなくて良いようにマスターフィルタ機能をもたせたほうがよさそうなので、次でmergeします。

いまはサマリーなどにも対応と何でもできるようにJSONpathでの切り出しなのですが、マージにあたりがん腫決め打ちとどちらが良いですか？

**Comment by piyotaicho** [comment]
そういやコンボボックスがあるので、プリセット式にしておきます。

**Comment by piyotaicho** [comment]
一応、ソースのパスを
$.[?(@.患者台帳)][?(@.がん種=="子宮頸がん")]^
でもできますが、これをマスターフィルタとするものを次のmerge(0.3.2)で実装します。

**Comment by akihikoueda** [comment]
ご検討ありがとうございます。
ご指摘の通り拡張性を考えるとJSONpathでの切り出し対応の方が汎用性が高そうですね。
先生のご提案のソースパスでの対応：$.[?(@.患者台帳)][?(@.がん種=="子宮頸がん")]^
が最も良さそうです。(例えば、今後研究目的で重複癌のデータをそれぞれ取得しにいくなどの利活用も考える場合もあると思われますので）
現行の作成ツールで上記のソースパス絞り込み指定が可能であればそちらを活用する方向でルール作成したいと考えます。

**Comment by akihikoueda** [comment]
お疲れ様です。
$.[?(@.患者台帳)][?(@.がん種=="子宮頸がん")]^ をソースに入れた際に、
ソース抽出結果では正しく閲覧できますが、この結果を用いて変数に代入し書き出ししようとするとワークしません。
これは次回のアップデートでワークするようにしていただけるというご予定との認識でよろしいでしょうか？

**Comment by akihikoueda** [comment]
追伸です：
患者台帳として、がん登録が1つの場合と、2つ以上の場合で、
一つの場合は $.[0].患者台帳.がん種 となりますが、2つ以上だと $.[0].患者台帳.[0].がん種 となるかと存じます。この辺りもルールツールに影響しますでしょうか？
