### ISSUE TITLE
卵巣がんの遠隔転移部位取得時にnull値が入る不具合について

### ISSUE THREAD

**Issue by akihikoueda** [piyotaicho/jesgosupport#3]
サポートツールを用いて卵巣がん台帳において

`$.[0].患者台帳.病期診断.pTNM.遠隔転移部位.[*]`

と取得しにいくと、下図のように [項目値, null] と
nullが入る形で出力されます。

同じ項目名である、`$.[0].患者台帳.病期診断.ypTNM.遠隔転移部位.[*]`
では null は入ってこないのですが、要因について調査いただけますでしょうか？

<img width="429" alt="スクリーンショット 2023-07-10 21 07 37" src="https://github.com/piyotaicho/jesgosupport/assets/49895496/5f81afbc-c801-4ceb-8309-e13d869dbb2e">

**Comment by piyotaicho** [comment]
これは、jesgoの方で発生しているようです。
取り急ぎ、ツールの読み込み側で緊急対応します。

**Comment by piyotaicho** [comment]
対応しました。根本的解決はスキーマとその実装ルーチンどちらか対応の早いほうで検討します。
https://github.com/piyotaicho/jesgosupport/releases/tag/0.3.2

**Comment by akihikoueda** [comment]
深夜にご対応誠にありがとうございました！
スキーマに関しては要改善点がありまとめて依頼させていただきます。
